### ISSUE TITLE
Question about Bottom_panel and automation

### ISSUE THREAD

**Issue by jo-me** [JulianKahnert/hygge#2]
Hey,

very nice theme!

I'm wondering, however, where the `bottom_panel `comes from that is mentioned in your example. 
Is this just some modular config or something special?

Also, did you build something so the screensaver mode is quit automatically on some event? For example, if you walk in front of the wallmountet display you could switch the UI based on the motion sensor. 
I'm thinking about using [WallPanel ](https://github.com/WallPanel-Project/wallpanel-android) as base app for a wallmounted Android tablet. It uses the camera as a motion sensor and/or turns on the display automatically if turned off.

Thanks
Jochen

**Comment by JulianKahnert** [comment]
Hey @jo-me , sry for the late response!
The `bottom_panel.yaml` looks like this:
```yaml
reload:
    widget_type: reload

panel_main:
    widget_type: navigate
    title: Main
    url: /main
    skin: hygge

panel_screensaver:
    widget_type: navigate
    title: Screensaver
    url: /screensaver
    skin: hygge

panel_weather:
    widget_type: navigate
    title: Weather
    url: /weather
    skin: hygge

layout:
    - script.all_on(1x1), script.all_off(1x1), panel_main(2x1), panel_screensaver(2x1), panel_weather(2x1)
```
So it is just some panel switching stuff. Currently I am using an old iPad Mini, which is always on. iOS gives you some kiosk mode feature, but you are right. A motion sensor would be awesome! Do you have finished your WallPanel project?
Best, Julian
